name: Deploy Preact App to GitHub Pages

on:
  push:
    branches:
      - web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        # working directory for all `run:` steps
        working-directory: frontend

    steps:
      # Check out your code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed so we can push history to gh-page

      - name: Cache bun packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lock') }}

      # Set up BUN
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      # Install dependencies & build
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build

      # Push the build folder to gh-page
      - name: Deploy to gh-page branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # the branch you set up for Pages
          publish_dir: frontend/dist
